// <auto-generated />
using System;
using AppointmentScheduling_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppointmentScheduling_API.Migrations
{
    [DbContext(typeof(AppointmentContext))]
    [Migration("20220316055557_AppointmentScheduleDB2")]
    partial class AppointmentScheduleDB2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppointmentScheduling_API.Models.Appointment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("endDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("meetingTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("p_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("physician")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("physicianId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("startDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("id")
                        .IsUnique();

                    b.ToTable("tblAppointmentDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
